# Required to adjust maintainability checks
version: "2"
checks:
  argument-count:
    config:
      threshold: 5
  method-complexity:
    config:
      threshold: 15 # Based on sonar-java
engines:
  sonar-java:
    enabled: true
      checks:
      # Most switches do not need to have default
      squid:SwitchLastCaseIsDefaultCheck:
        enabled: false
      # Check if case statements are broken, some switches need to fall through
      squid:S128:
        enabled: false
      # Check if function is empty, explanations are often in JavaDoc
      squid:S1186:
        enabled: false
      # Check if the string "password" is in string constants, triggered too many false positives
      squid:S2068:
        enabled: false