engines:
  # ... CONFIG CONTENT ...
  sonar-java:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      # Check if function is empty, explanations are often in JavaDoc
      squid:S1186:
        enabled: false
      # Most switches do not need to have default
      squid:SwitchLastCaseIsDefaultCheck:
        enabled: false
# ... CONFIG CONTENT ...