engines:
  # ... CONFIG CONTENT ...
  sonar-java:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      # Most switches do not need to have default
      squid:SwitchLastCaseIsDefaultCheck:
        enabled: false
      # Check if case statements are broken, some switches need to fall through
      squid:S128:
        enabled: false
      # Check if function is empty, explanations are often in JavaDoc
      squid:S1186:
        enabled: false
      # Check if the string "password" is in string constants, triggered too many false positives
      squid:S2068:
        enabled: false
# ... CONFIG CONTENT ...