---
kind: pipeline
name: sa-ci-test

steps:
  - name: java-push-test
    image: nextcloudci/android:android-54
    # Keystore properties not included in order to trigger isLocal = false automatically
    # Can only test with debug as other build configs require a keystore
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx512m -XX:+HeapDumpOnOutOfMemoryError"'
      _JAVA_OPTIONS: "-Xms512m -Xmx1536m"
    commands:
      - ./gradlew testDebugUnitTest
    when:
      branch:
        include:
          - master
      event:
        - push
        - pull_request

  - name: java-pr-test
    image: nextcloudci/android:android-54
    # Keystore properties not included in order to trigger isLocal = false automatically
    # Can only test with debug as other build configs require a keystore
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx512m -XX:+HeapDumpOnOutOfMemoryError"'
      _JAVA_OPTIONS: "-Xms512m -Xmx1536m"
    commands:
      - ./gradlew testDebugUnitTest
    when:
      branch:
        exclude:
          - master
      event:
        - pull_request

trigger:
  event:
    - push